{
 "title": "Thumbnail Generator Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Total execution time (ms) - AVG ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "1000 *\r\n(\r\n  sum by (service) (\r\n    rate(app_total_execution_time_seconds_sum{operation=\"generate_thumbnail\", method=\"POST\"}[5m])\r\n  )\r\n/\r\n  clamp_min(\r\n    sum by (service) (\r\n      rate(app_total_execution_time_seconds_count{operation=\"generate_thumbnail\", method=\"POST\"}[5m])\r\n    ),\r\n    1\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Internal processing time (ms) - AVG",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "1000 *\r\n(\r\n  sum by (service) (\r\n    rate(app_internal_processing_time_seconds_sum{method=\"POST\", operation=\"generate_thumbnail\"}[5m])\r\n  )\r\n/\r\n  clamp_min(\r\n    sum by (service) (\r\n      rate(app_internal_processing_time_seconds_count{method=\"POST\", operation=\"generate_thumbnail\"}[5m])\r\n    ),\r\n    1\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total execution time (ms) - P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "1000 * histogram_quantile(\r\n  0.95,\r\n  sum by (service, le) (\r\n    rate(app_total_execution_time_seconds_bucket{operation=\"generate_thumbnail\", method=\"POST\"}[5m])\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Internal processing time (ms) - P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "1000 * histogram_quantile(\r\n  0.95,\r\n  sum by (service, le) (\r\n    rate(app_internal_processing_time_seconds_bucket{method=\"POST\", operation=\"generate_thumbnail\"}[5m])\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total execution time (ms) - P99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "1000 * histogram_quantile(\r\n  0.99,\r\n  sum by (service, le) (\r\n    rate(app_total_execution_time_seconds_bucket{operation=\"generate_thumbnail\", method=\"POST\"}[5m])\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Internal processing time (ms)  - P99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "1000 * histogram_quantile(\r\n  0.99,\r\n  sum by (service, le) (\r\n    rate(app_internal_processing_time_seconds_bucket{method=\"POST\", operation=\"generate_thumbnail\"}[5m])\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage APP (%) - AVG",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "avg by (service) (\r\n  avg_over_time(app_cpu_usage_percent{environment=\"production\", operation=\"generate_thumbnail\"}[5m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM usage APP (mb) - AVG",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "avg by (service) (\r\n  avg_over_time(app_ram_usage_mb{environment=\"production\", operation=\"generate_thumbnail\"}[5m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage APP (%) - PEAK",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "max by (service) (\r\n  max_over_time(app_cpu_peak_percent{environment=\"production\", operation=\"generate_thumbnail\"}[5m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM usage APP (mb) - PEAK",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "max by (service) (\r\n  max_over_time(app_ram_peak_mb{environment=\"production\", operation=\"generate_thumbnail\"}[5m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total CPU (%) - INFRA",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "avg_over_time((\r\n  100 * (\r\n    1 -\r\n    sum by (service)(rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) /\r\n    sum by (service)(rate(node_cpu_seconds_total[1m]))\r\n  )\r\n)[$__range:])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total RAM (mb) - INFRA",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "avg_over_time((\r\n  sum by (service) (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes)\r\n)[$__range:]) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total CPU PEAK (%) - INFRA",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "max_over_time((\r\n  100 * (\r\n    1 -\r\n    sum by (service)(rate(node_cpu_seconds_total{mode=\"idle\"}[1m]))\r\n    /\r\n    sum by (service)(rate(node_cpu_seconds_total[1m]))\r\n  )\r\n)[$__range:])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total RAM (mb) PEAK - INFRA",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "max_over_time((\r\n  sum by (service) (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes)\r\n)[$__range:]) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Communication Latency (ms) - AVG (http.response_time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "avg(artillery_summaries{metric=\"http_response_time_mean\"}) by (service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput (req/s) - (http.request_rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "avg(artillery_rates{metric=\"http_request_rate\"}) by (service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Communication Latency (ms) - P95 (http.response_time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "avg(artillery_summaries{metric=\"http_response_time_p95\"}) by (service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Communication Latency (ms) - P99 (http.response_time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "avg(artillery_summaries{metric=\"http_response_time_p99\"}) by (service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Error Rate 4xx (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "100 * (1 - (\r\n  sum(artillery_summaries{metric=\"http_response_time_2xx_count\"}) by (service)\r\n  /\r\n  sum(artillery_summaries{metric=\"http_response_time_count\"}) by (service)\r\n))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Error Rate 5xx (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "targets": [
    {
     "expr": "100 * (\r\n  1 - (\r\n    sum(artillery_summaries{metric=\"http_response_time_2xx_count\"}) by (service)\r\n    /\r\n    sum(artillery_summaries{metric=\"http_response_time_count\"}) by (service)\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failure rate per invocation (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "100 * (\r\n  1 - (\r\n    sum(artillery_summaries{metric=\"http_response_time_2xx_count\"}) by (service)\r\n    /\r\n    sum(artillery_summaries{metric=\"http_response_time_count\"}) by (service)\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Availability (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "targets": [
    {
     "expr": "100 * (\r\n  sum(artillery_summaries{metric=\"http_response_time_2xx_count\"}) by (service)\r\n  /\r\n  sum(artillery_summaries{metric=\"http_response_time_count\"}) by (service)\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cold Start (ms) - Lambda",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "(\r\n  increase(app_cold_start_duration_seconds_sum{environment=\"production\"}[30m])\r\n/\r\n  clamp_min(\r\n    increase(app_cold_start_duration_seconds_count{environment=\"production\"}[30m]),\r\n    1\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}