{
 "title": "API Rest Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "RAM usage APP PEAK (process_ram_megabytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "round(\r\n  max by (instance) (\r\n    max_over_time(anilove_app_memory_rss_bytes[15m])\r\n  ) / 1024^2,\r\n  0.01\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latência de Comunicação - AVG (http.response_time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg(artillery_summaries{metric=\"http_response_time_mean\"}) by (service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage APP PEAK % (process_cpu_percent)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "round(\r\n  clamp_max(\r\n    max by (instance) (\r\n      max_over_time(anilove_app_cpu_percent[15m])\r\n    ),\r\n    100\r\n  ),\r\n  0.01\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latência de Comunicação - P99 (http.response_time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "avg(artillery_summaries{metric=\"http_response_time_p99\"}) by (service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tempo total de execução - P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le, instance) (\r\n    rate(anilove_http_request_duration_seconds_bucket[15m])\r\n  )\r\n) * 1000\r\n\r\n\r\n\r\n\r\n  ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tempo de processamento interno - P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le, instance) (\r\n    rate(anilove_internal_processing_duration_seconds_bucket[15m])\r\n  )\r\n) * 1000\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tempo total de execução - AVG ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "1000 *\r\nsum by (le, instance) (\r\n  rate(anilove_http_request_duration_seconds_sum[15m])\r\n)\r\n/\r\nclamp_min(\r\n  sum by (le, instance) (\r\n    rate(anilove_http_request_duration_seconds_count[15m])\r\n  ),\r\n  1e-9\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput (http.request_rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "avg by (service) (\r\n  artillery_rates{metric=\"http_request_rate\"}\r\n) * 1000\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tempo total de execução - P99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.99,\r\n  sum by (le, instance) (\r\n    rate(anilove_http_request_duration_seconds_bucket[15m])\r\n  )\r\n) * 1000\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage APP % (process_cpu_percent)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "avg by (instance) (\r\n  avg_over_time(anilove_app_cpu_percent[15m])\r\n)\r\n\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latência de Comunicação - P95 (http.response_time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "avg(artillery_summaries{metric=\"http_response_time_p95\"}) by (service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM usage APP (process_ram_megabytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "round(\r\n  avg by (instance) (\r\n    avg_over_time(anilove_app_memory_rss_bytes[15m])\r\n  ) / 1024^2,\r\n  0.01\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tempo de processamento interno - AVG",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "0.00001 *\r\nsum by (le, instance) (\r\n  rate(anilove_internal_processing_duration_seconds_sum[15m])\r\n)\r\n/\r\nclamp_min(\r\n  sum by (instance) (\r\n    rate(anilove_internal_processing_duration_seconds_count[5m])\r\n  ),\r\n  1e-9\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Taxa de erro HTTP 5xx (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "100 * (\r\n  1 - (\r\n    sum(artillery_summaries{metric=\"http_response_time_2xx_count\"}) by (service)\r\n    /\r\n    sum(artillery_summaries{metric=\"http_response_time_count\"}) by (service)\r\n  )\r\n)\r\n\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tempo de processamento interno - P99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.99,\r\n  sum by (le, instance) (\r\n    rate(anilove_internal_processing_duration_seconds_bucket[15m])\r\n  )\r\n) * 1000\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disponibilidade (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "100 * (\r\n  sum(artillery_summaries{metric=\"http_response_time_2xx_count\"}) by (service)\r\n  /\r\n  sum(artillery_summaries{metric=\"http_response_time_count\"}) by (service)\r\n)\r\n\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Total (%) - INFRA",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "1000 *\r\nsum by (instance) (rate(node_cpu_seconds_total{mode!=\"idle\"}[15m])) \r\n/\r\nsum by (instance) (rate(node_cpu_seconds_total[15m]))\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Taxa de falhas por invocação (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "100 * (\r\n  1 - (\r\n    sum(artillery_summaries{metric=\"http_response_time_2xx_count\"}) by (service)\r\n    /\r\n    sum(artillery_summaries{metric=\"http_response_time_count\"}) by (service)\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Total (%) - INFRA",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "avg(\r\n  100 * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes))\r\n) by (instance)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Taxa de Erro HTTP 4xx (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "targets": [
    {
     "expr": "100 * (1 - (\r\n  sum(artillery_summaries{metric=\"http_response_time_2xx_count\"}) by (service)\r\n  /\r\n  sum(artillery_summaries{metric=\"http_response_time_count\"}) by (service)\r\n))\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cold Start AVG, P95 and P99 (Lambda)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "label_replace(\r\n  (\r\n    sum(anilove_lambda_cold_start_duration_seconds_sum{job=\"instrumented-metrics-lambda\"})\r\n  /\r\n    sum(anilove_lambda_cold_start_duration_seconds_count{job=\"instrumented-metrics-lambda\"})\r\n  ),\r\n  \"service\", \"Lambda Cold Start Avg\", \"job\", \".*\"\r\n)\r\n\r\n\r\n\r\n\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\r\n  sum(increase(anilove_lambda_cold_start_duration_seconds_sum[6h]))\r\n  /\r\n  clamp_min(sum(increase(anilove_lambda_cold_start_duration_seconds_count[6h])), 1),\r\n  \"service\", \"Lambda Cold Start Avg (ms)\", \"service\", \".*\"\r\n)\r\n\r\n\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\r\n  histogram_quantile(\r\n    0.99,\r\n    sum(anilove_lambda_cold_start_duration_seconds_bucket) by (le)\r\n  ) * 1000 ,\r\n  \"service\", \"Lambda Cold Start (p99)\", \"service\", \".*\"\r\n)\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}